import {
    AlarmClock,
    ArrowBigRightDash,
    ArrowRightCircle,
    AlertCircle,
    BadgeCheck,
    BarChart3,
    Bell,
    BetweenHorizontalStart,
    Bot,
    BrainCircuit,
    CircleHelp,
    Clock3,
    FilePenLine,
    FileSearch,
    FolderGit2,
    GitBranch,
    ListChecks,
    MessageSquare,
    MessageSquareMore,
    MessageSquareQuote,
    Package,
    Play,
    Split,
    Square,
    Tag,
    Ticket,
    UserCog,
    UserPlus,
    Workflow,
    Wrench,
} from 'lucide-vue-next';

const FLOW_ICON_REGISTRY = {
    play: Play,
    condition: GitBranch,
    switch: Split,
    message: MessageSquare,
    question: CircleHelp,
    quick_reply: ListChecks,
    template: MessageSquareQuote,
    wait: Clock3,
    set_field: FilePenLine,
    get_field: FileSearch,
    set_tag: Tag,
    remove_tag: Tag,
    jump: ArrowBigRightDash,
    ticket: Ticket,
    status: Wrench,
    handoff: UserCog,
    assign: UserPlus,
    notify: Bell,
    log: FolderGit2,
    analytics: BarChart3,
    ai_intent: BrainCircuit,
    ai_reply: Bot,
    stop: Square,
    node: Workflow,
    category_control: BetweenHorizontalStart,
    category_messaging: MessageSquareMore,
    category_contact: Tag,
    category_service: Ticket,
    category_ai: Bot,
    category_operations: BarChart3,
    starter_welcome: MessageSquare,
    starter_lead: UserPlus,
    starter_handoff: UserCog,
    starter_appointment: AlarmClock,
    starter_faq: Bot,
    conversation_system: MessageSquare,
    conversation_user: CircleHelp,
    conversation_branch: GitBranch,
    conversation_wait: Clock3,
    conversation_end: Square,
    conversation_start: Play,
    conversation_unknown: ArrowRightCircle,
    severity_warning: AlertCircle,
    severity_info: BadgeCheck,
    block_text: MessageSquare,
    block_media: MessageSquareQuote,
    block_buttons: ListChecks,
    block_list: MessageSquareMore,
    block_product_card: Package,
    block_product_gallery: Package,
};

export const getFlowIconComponent = (iconKey) => FLOW_ICON_REGISTRY[iconKey] || FLOW_ICON_REGISTRY.node;
