<?php

namespace Tests\Feature;

use Symfony\Component\Process\Process;
use Tests\TestCase;

class BackendTranslationAuditTest extends TestCase
{
    public function test_backend_user_messages_are_localized(): void
    {
        $outputDir = base_path('tmp');
        $script = base_path('scripts/i18n/audit-backend-translations.php');
        $outputFile = $outputDir . DIRECTORY_SEPARATOR . 'i18n-audit-backend-test.json';

        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0777, true);
        }

        $process = new Process([
            PHP_BINARY,
            $script,
            '--format=json',
            '--out=' . $outputFile,
            '--fail-on-backend-untranslated=1',
        ]);
        $process->run();

        $this->assertSame(
            0,
            $process->getExitCode(),
            "Backend i18n audit command failed:\n" . $process->getErrorOutput() . $process->getOutput()
        );

        $reportRaw = file_get_contents($outputFile);
        $this->assertNotFalse($reportRaw, 'Unable to read backend i18n audit report.');

        $report = json_decode($reportRaw, true);
        $this->assertIsArray($report, 'Invalid JSON generated by backend i18n audit script.');

        $this->assertSame(
            0,
            (int) ($report['summary']['backend_untranslated_messages'] ?? -1),
            'Detected untranslated backend user-facing messages.'
        );
    }
}
