<?php

namespace Tests\Feature;

use Symfony\Component\Process\Process;
use Tests\TestCase;

class UiOptionsLocalizationAuditTest extends TestCase
{
    public function test_guarded_dropdown_sources_are_localized(): void
    {
        $outputDir = base_path('tmp');
        $script = base_path('scripts/i18n/audit-ui-options.php');
        $outputFile = $outputDir . DIRECTORY_SEPARATOR . 'i18n-audit-options-guard-test.json';

        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0777, true);
        }

        $process = new Process([
            PHP_BINARY,
            $script,
            '--format=json',
            '--out='.$outputFile,
            '--fail-on-options-unlocalized=1',
        ]);
        $process->run();

        $this->assertSame(
            0,
            $process->getExitCode(),
            "Options audit command failed:\n" . $process->getErrorOutput() . $process->getOutput()
        );

        $reportRaw = file_get_contents($outputFile);
        $this->assertNotFalse($reportRaw, 'Unable to read options audit report.');

        $report = json_decode($reportRaw, true);
        $this->assertIsArray($report, 'Invalid JSON generated by options audit script.');

        $this->assertSame(
            0,
            (int) ($report['summary']['options_unlocalized_sources'] ?? -1),
            'Detected unlocalized options sources in guarded files.'
        );
    }
}
