<?php

namespace Tests\Feature;

use Symfony\Component\Process\Process;
use Tests\TestCase;

class UiTranslationAuditTest extends TestCase
{
    public function test_full_ui_audit_has_no_missing_ar_en_or_untranslated_template_text(): void
    {
        $outputDir = base_path('tmp');
        $staticScript = base_path('scripts/i18n/audit-ui-translations.php');
        $astScript = base_path('scripts/i18n/audit-ui-template-ast.mjs');
        $optionsScript = base_path('scripts/i18n/audit-ui-options.php');
        $mergeScript = base_path('scripts/i18n/audit-ui-merge.php');

        $staticOutputFile = $outputDir . DIRECTORY_SEPARATOR . 'i18n-audit-static-test.json';
        $astOutputFile = $outputDir . DIRECTORY_SEPARATOR . 'i18n-audit-ast-test.json';
        $optionsOutputFile = $outputDir . DIRECTORY_SEPARATOR . 'i18n-audit-options-test.json';
        $mergedOutputFile = $outputDir . DIRECTORY_SEPARATOR . 'i18n-audit-merged-test.json';

        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0777, true);
        }

        $staticProcess = new Process([
            PHP_BINARY,
            $staticScript,
            '--locales=ar,en',
            '--scope=all',
            '--format=json',
            '--out='.$staticOutputFile,
            '--fail-on-missing-ar=1',
            '--fail-on-missing-en=1',
            '--fail-on-literal-untranslated=1',
            '--fail-on-ar-equals-en=1',
            '--fail-on-en-default-drift=1',
        ]);
        $staticProcess->run();
        $this->assertSame(
            0,
            $staticProcess->getExitCode(),
            "Static i18n audit command failed:\n" . $staticProcess->getErrorOutput() . $staticProcess->getOutput()
        );

        $astProcess = new Process([
            'node',
            $astScript,
            '--scope=all',
            '--format=json',
            '--out='.$astOutputFile,
            '--fail-on-template-untranslated=1',
        ]);
        $astProcess->run();
        $this->assertSame(
            0,
            $astProcess->getExitCode(),
            "AST i18n audit command failed:\n" . $astProcess->getErrorOutput() . $astProcess->getOutput()
        );

        $optionsProcess = new Process([
            PHP_BINARY,
            $optionsScript,
            '--format=json',
            '--out='.$optionsOutputFile,
            '--fail-on-options-unlocalized=1',
        ]);
        $optionsProcess->run();
        $this->assertSame(
            0,
            $optionsProcess->getExitCode(),
            "Options i18n audit command failed:\n" . $optionsProcess->getErrorOutput() . $optionsProcess->getOutput()
        );

        $mergeProcess = new Process([
            PHP_BINARY,
            $mergeScript,
            '--static='.$staticOutputFile,
            '--ast='.$astOutputFile,
            '--options='.$optionsOutputFile,
            '--format=json',
            '--out='.$mergedOutputFile,
            '--fail-on-missing-ar=1',
            '--fail-on-missing-en=1',
            '--fail-on-literal-untranslated=1',
            '--fail-on-template-untranslated=1',
            '--fail-on-options-unlocalized=1',
            '--fail-on-ar-equals-en=1',
            '--fail-on-en-default-drift=1',
        ]);
        $mergeProcess->run();

        $this->assertSame(
            0,
            $mergeProcess->getExitCode(),
            "Merged i18n audit command failed:\n" . $mergeProcess->getErrorOutput() . $mergeProcess->getOutput()
        );

        $reportRaw = file_get_contents($mergedOutputFile);
        $this->assertNotFalse($reportRaw, 'Unable to read merged i18n audit report.');

        $report = json_decode($reportRaw, true);
        $this->assertIsArray($report, 'Invalid JSON generated by merged i18n audit script.');

        $staticReportRaw = file_get_contents($staticOutputFile);
        $this->assertNotFalse($staticReportRaw, 'Unable to read static i18n audit report.');

        $staticReport = json_decode($staticReportRaw, true);
        $this->assertIsArray($staticReport, 'Invalid JSON generated by static i18n audit script.');

        $summary = $report['summary'] ?? [];

        $this->assertSame(
            0,
            (int) ($summary['missing_in_ar'] ?? -1),
            'Arabic translation coverage failed in full scope.'
        );

        $this->assertSame(
            0,
            (int) ($summary['missing_in_en'] ?? -1),
            'English translation coverage failed in full scope.'
        );

        $this->assertSame(
            0,
            (int) ($summary['missing_total_unique'] ?? -1),
            'Found missing translation keys in full scope.'
        );

        $this->assertSame(
            0,
            (int) ($summary['missing_escaped_unique'] ?? -1),
            'Found missing escaped translation keys in full scope.'
        );

        $this->assertSame(
            0,
            (int) ($summary['literal_untranslated'] ?? -1),
            'Found non-allowlisted untranslated literals in full scope.'
        );

        $this->assertSame(
            0,
            (int) ($summary['template_text_untranslated'] ?? -1),
            'Found untranslated template text in full scope.'
        );

        $this->assertSame(
            0,
            (int) ($summary['options_unlocalized_sources'] ?? -1),
            'Found unlocalized dropdown option sources in guarded pages.'
        );

        $this->assertSame(
            0,
            (int) ($summary['ar_equal_en_nontechnical'] ?? -1),
            'Found AR values equal to EN values for non-technical text.'
        );

        $this->assertSame(
            0,
            (int) ($summary['en_default_drift'] ?? -1),
            'Found drift between en.json and default_en.json.'
        );

        $this->assertContains(
            "You don't have any campaigns",
            $staticReport['escaped_keys_detected'] ?? [],
            'Escaped apostrophe keys are not detected by translation key extraction.'
        );
    }
}
