<?php

return [
    'route_snapshot' => [
        'total_count' => 350,
        'allowed_total_counts' => [349, 350],
        'critical_routes' => [
            ['method' => 'GET', 'uri' => 'health/live', 'name' => null],
            ['method' => 'GET', 'uri' => 'health/ready', 'name' => null],
            ['method' => 'GET', 'uri' => 'automation/flows', 'name' => 'flowbuilder.index'],
            ['method' => 'POST', 'uri' => 'automation/flows/{uuid}/publish', 'name' => 'flowbuilder.publish'],
            ['method' => 'POST', 'uri' => 'automation/flows/{uuid}/duplicate', 'name' => 'flowbuilder.duplicate'],
            ['method' => 'GET', 'uri' => 'automation/flows/{uuid}/assets/{assetUuid}', 'name' => 'flowbuilder.assets.show'],
            ['method' => 'GET|HEAD', 'uri' => 'automation/chat/suggestion', 'name' => null],
            ['method' => 'POST', 'uri' => 'api/send', 'name' => null],
            ['method' => 'POST', 'uri' => 'api/send/template', 'name' => null],
            ['method' => 'POST', 'uri' => 'api/send/media', 'name' => null],
            ['method' => 'POST', 'uri' => 'api/campaigns', 'name' => null],
            ['method' => 'GET', 'uri' => 'api/contacts', 'name' => null],
            ['method' => 'GET', 'uri' => 'api/templates', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'admin/settings/features/embedded-signup/health', 'name' => null],
            ['method' => 'POST', 'uri' => 'admin/settings/features/embedded-signup/meta-review-tests', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'admin/settings/features/embedded-signup', 'name' => null],
            ['method' => 'POST', 'uri' => 'admin/settings/features/embedded-signup', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'admin/settings/features/ai-assistant', 'name' => null],
            ['method' => 'POST', 'uri' => 'admin/settings/features/ai-assistant', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'admin/settings/features/flow-builder', 'name' => null],
            ['method' => 'POST', 'uri' => 'admin/settings/features/flow-builder', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'webhook/waba', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'webhook/whatsapp/{identifier?}', 'name' => null],
            ['method' => 'GET|HEAD', 'uri' => 'settings/company-team', 'name' => 'company.team'],
            ['method' => 'POST', 'uri' => 'settings/features/embedded-signup/toggle', 'name' => null],
            ['method' => 'POST', 'uri' => 'settings/company-team/invite', 'name' => 'company.team.invite'],
            ['method' => 'PUT', 'uri' => 'settings/company-team/{uuid}', 'name' => 'company.team.update'],
            ['method' => 'POST', 'uri' => 'settings/company-team/{uuid}/resend-invite', 'name' => 'company.team.resend-invite'],
            ['method' => 'DELETE', 'uri' => 'settings/company-team/{uuid}', 'name' => 'company.team.destroy'],
            ['method' => 'PATCH', 'uri' => 'admin/users/{user}/suspend', 'name' => 'users.suspend'],
            ['method' => 'PATCH', 'uri' => 'admin/users/{user}/restore', 'name' => 'users.restore'],
        ],
    ],
    'budgets' => [
        'previous_caps' => [
            'app/Services/WhatsappService.php' => 2232,
            'app/Http/Controllers/User/SettingController.php' => 1044,
            'app/Http/Controllers/ApiController.php' => 1000,
            'app/Services/ChatService.php' => 759,
            'app/Services/AutomationFlows/AutomationFlowRuntimeService.php' => 832,
            'resources/js/Pages/User/Automation/Flows/Builder.vue' => 1447,
            'resources/js/Pages/User/Dashboard.vue' => 4243,
            'resources/js/Components/AutomationFlows/FlowPreviewDrawer.vue' => 1446,
            'app/Services/CompanyWorkforceService.php' => 1457,
            'app/Services/OrganizationService.php' => 1209,
            'app/Services/BillingInvoiceService.php' => 1080,
        ],
        'build_chunks' => [
            'app-core' => 225,
            'flow-builder-core' => 500,
            'editor-libs' => 500,
            'media-tools' => 500,
            'phone-input' => 500,
            'realtime' => 125,
            'charting' => 550,
            'icon-libs' => 500,
            'overlay-libs' => 500,
            'ui-vue-libs' => 500,
            'utility-libs' => 50,
        ],
        'build_assets' => [
            'max_js_kb' => 550,
        ],
        'modules' => [
            'controller' => 250,
            'application' => 200,
            'domain' => 150,
            'infrastructure' => 250,
            'support' => 200,
        ],
        'route_file' => 150,
        'vue_page' => 350,
        'vue_component' => 200,
    ],
];
